### ISSUE TITLE
Change things so it is more clear that type definitions must come after all other statements in the Enumerations level.

### ISSUE THREAD

**Issue by rbwhitaker** [rbwhitaker/CSharpPlayersGuideEarlyAccess#372]

**Comment by Rewstyr** [comment]
This could be as easy as having it all together:

using System; 

Season current = Season.Spring;
Console.WriteLine($"I love ${current}");

enum Season { Winter, Spring, Summer, Fall }

**Comment by rbwhitaker** [comment]
I might just yoink that sample, @Rewstyr!

**Comment by Rewstyr** [comment]
Will that make me a published author?? 8-P

**Comment by rbwhitaker** [comment]
![image](https://user-images.githubusercontent.com/3482875/110588144-db721700-8131-11eb-8e75-a4273f0cf9aa.png)

**Comment by rbwhitaker** [comment]
![image](https://user-images.githubusercontent.com/3482875/110588396-33a91900-8132-11eb-9672-6c15c30b0238.png)
