### ISSUE TITLE
Minor Grammar error

### ISSUE THREAD

**Issue by AikyouSatou** [rbwhitaker/CSharpPlayersGuideEarlyAccess#430]
On page 23 physical edition, "Expressions" Second paragraph, the book reads "While we do could this:" and it should read "While we could do this:"

**Comment by rbwhitaker** [comment]
Thanks for reporting this, @AikyouSatou! Physical books can't be updated once printed (unfortunately) but I've got an errata for this added now (posting momentarily) and the next digital update should have this fixed as well.
