### ISSUE TITLE
top of Chapter 53 has label for Bonus Level A

### ISSUE THREAD

**Issue by odigity** [rbwhitaker/CSharpPlayersGuideEarlyAccess#445]
Just bought new copy of 4th edition on Amazon, noticed the labels at the very top of the page on Chapter 53 are actually for Bonus Level A.

**Comment by rbwhitaker** [comment]
Thanks for the report, @odigity! I've fixed it for future digital updates (starting in 4.0.5). I'll get it into print updates as soon as I can, though that's a much longer process.
