### ISSUE TITLE
Minor "style issue" for Pg. 26, “Consolas and Telim”

### ISSUE THREAD

**Issue by Matthew-Tate-Scarbrough** [rbwhitaker/CSharpPlayersGuideEarlyAccess#612]
If you would like, I could reopen this issue again later suppose I should find more than these, but I would like to note that it might be beneficial (however little) to add a notice to it that it generates a Compiler Warning, `CS8600`.

The very next page mentions it, but I think it could be a good thing to mention, “Sometimes the correct solution may give a warning—this isn't always a bad thing,” or something like that.

Just a minor nitpick.

**Comment by rbwhitaker** [comment]
I've added this as a note in the challenge's objectives in 6th Edition. I do think it will add clarity for people doing the challenge who may pick up on that warning and wonder if they've done something wrong. It's completely expected at this point, and there's nothing you can do about it yet, given the very limited set of tools available to you.

The change was simple enough that I may still consider putting that one line into the 5.0.2 patch update.
